### ISSUE TITLE
How to help on this extension

### ISSUE THREAD

**Issue by Theosakamg** [colcon/colcon-gradle#1]
I would add/contribute to support [Gradle](https://gradle.org/) projects.
For : 
- Java/JVM
- Android

I can't fork the project (because is empty) for PR. Can you help me ?

**Comment by Theosakamg** [comment]
Connected to https://github.com/ros2java-alfred/ros2_java/issues/14

**Comment by Theosakamg** [comment]
Temporary repository : https://github.com/Theosakamg/colcon-gradle

**Comment by dirk-thomas** [comment]
@esteve FYI

**Comment by esteve** [comment]
@dirk-thomas thanks for the heads up. I'll upload the code shortly, it's based on the work I already did for `ros2_java`
