### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by calvertdw** [colcon/colcon-gradle#14]
I wrote a [meta build system for ihmcrobotics](https://github.com/ihmcrobotics/ihmc-build) that I think has a lot of logical overlap to colcon so I'm interested to see if we could make this work for us.

**Comment by esteve** [comment]
That's great! This has a different goal, though. `colcon-gradle` is just a mechanism for integrating pure Gradle projects (i.e. non-ROS) into `colcon`. For a `ros2-java`-specific Gradle plugin, you may have a look at https://plugins.gradle.org/plugin/org.ros2.tools.gradle

**Comment by esteve** [comment]
In any case, feel free to submit PRs, I'm happy to review them.

**Comment by calvertdw** [comment]
My plugin does package searching and selection on what to build. That part I would like to delegate to colcon.

**Comment by calvertdw** [comment]
@Theosakamg @esteve Do you guys have some examples packages to test this out?

**Comment by esteve** [comment]
Any standard (i.e. non-ROS) Gradle program should run.

**Comment by esteve** [comment]
> My plugin does package searching and selection on what to build. That part I would like to delegate to colcon.

In that case, perhaps `colcon` may not be useful to you. What other features does your plugin have?

**Comment by esteve** [comment]
Ah, understood, I thought that your plugin did something else besides package management. In that case, yeah I agree, using `colcon` for that is a great idea.

I'm closing this issue, you're definitely welcome to contribute :-) Give `colcon` and `colcon-gradle` a try and see if it works for you and let's see what can be improved. Thanks!
