### ISSUE TITLE
Default task is actually `assemble`

### ISSUE THREAD

**Issue by calvertdw** [colcon/colcon-gradle#21]
I assume this documentation is incorrect, or are you referring to `colcon build`?

https://github.com/colcon/colcon-gradle/blob/38f18452ca986bf50b1d8651636edcd681a831d5/colcon_gradle/task/gradle/build.py#L117-L121

**Comment by calvertdw** [comment]
![image](https://user-images.githubusercontent.com/1161586/43163207-0e375d90-8f53-11e8-8755-3800111b76d1.png)

**Comment by Theosakamg** [comment]
Explanation on #6

**Comment by esteve** [comment]
@calvertdw yeah, it was an inconsistency, fixed in https://github.com/colcon/colcon-gradle/commit/cad2404620e3c4c58b9c305b35ac8a39770bb3cc Thanks for the heads up!
