### ISSUE TITLE
"local" vs. "wrapper" language

### ISSUE THREAD

**Issue by calvertdw** [colcon/colcon-gradle#23]
Why do we have two different terms for wrapper? Can we refactor "local" to "wrapper" everywhere?

https://github.com/colcon/colcon-gradle/blob/38f18452ca986bf50b1d8651636edcd681a831d5/colcon_gradle/task/gradle/__init__.py#L86

**Comment by Theosakamg** [comment]
I think we can rename :
- `has_local_executable` to `has_wrapper_executable`
- `get_local_executable` to `get_wrapper_executable`

@esteve do you agree with that?

**Comment by esteve** [comment]
Closed via #25
